### ISSUE TITLE
Support MariaDB 10.2

### ISSUE THREAD

**Issue by lazydays79** [primekeydevs/ejbca-ce#22] opened 2022-01-28 16:49 UTC
With ejbca releases > 7.4.3.3, the support of mariadb 10.2 dropped:

~~~
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Unknown table 'sequences' in information_schema
Query is : select SEQUENCE_CATALOG, SEQUENCE_SCHEMA, SEQUENCE_NAME, INCREMENT from information_schema.sequences
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:870)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:575)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:256)
	... 23 more
~~~

This can be avoided using org.hibernate.dialect.MariaDB102Dialect. 

I will provide a pull request which should fix this issue.

Kind regards,
Michael

**Comment by primetomas** [comment] 2022-01-31 09:41
This is odd. Are you sure you didn't deploy forgetting to set "database.name=mysql" in database.properties?

I just tried with an empty database with the default dialect of:
org.hibernate.dialect.MySQL5InnoDBDialect
using 
mysql --version
mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

And it worked fine. Usually the "sequence" error occurs if the database dialect is set for the H2 database (the default if you don't configure database.properties).

**Comment by lazydays79** [comment] 2022-01-31 11:03
Yes, I'm sure. We tried to update our offline root CA from 7.4.3.3 to 7.5.0. After deployment and starting wildfly up again this error occurs and the deployment failed.

**Comment by primetomas** [comment] 2022-01-31 11:13
Can you specify your components in detail. What versions of everything.
I'd rather not have different configuration setting for different versions of MariaDB. Since the org.hibernate.dialect.MySQL5InnoDBDialect works with MariaDB 10.3 I would like to find the cause why it does not work with your MariaDB 10.2.

**Comment by primetomas** [comment] 2022-01-31 11:17
Where did you get EJBCA 7.5.0 from? Git clone?

**Comment by lazydays79** [comment] 2022-01-31 11:38
> Can you specify your components in detail. What versions of everything. I'd rather not have different configuration setting for different versions of MariaDB. Since the org.hibernate.dialect.MySQL5InnoDBDialect works with MariaDB 10.3 I would like to find the cause why it does not work with your MariaDB 10.2.

This is because information_scheme.sequences was introduced in Maria DB 10.3 😊

**Comment by lazydays79** [comment] 2022-01-31 11:39
> Where did you get EJBCA 7.5.0 from? Git clone?

I'm working at Atos where we have an enterprise license from ejbca. Today and tomorrow I'm on vacation, but I think I can gather more facts on Wednesday.

**Comment by primetomas** [comment] 2022-01-31 11:42
MySQL5InnoDBDialect is way older than MariaDB 10.3 though, so still strange, I have been using that dialect since MariaDB 5... Did you also upgrade MariaDB when you upgraded you Root CA?
For Enterprise, could you create a support ticket (reference this issue if you like)? Then we have the desired SLA traceability and we can easier dig into details to figure out exactly what is going on.

Have a great vacation.

**Comment by lazydays79** [comment] 2022-01-31 14:05
No, the database was not touched during the update.

If you like, we can create a support ticket. But our experience with the last tickets let's us think that this won't help us at all.

None of our last technical issues have been solved and all of the tickets endet in a "please send logs - cannot reproduce" ping pong.

This github issue here is already much more successful, so thank you for answer so far. 😊

Kind regards,
Michael

**Comment by primetomas** [comment] 2022-01-31 14:37
Please create a ticket, reference me, we want to make you a good experience.

**Comment by lazydays79** [comment] 2022-02-07 08:36
Ticket #10921 has been raised now.

Sorry for the delay, after my vacation I was ill.

**Comment by primetomas** [comment] 2022-02-07 08:54
Thanks, closing this issue.

**Closed by primetomas** 2022-02-07 08:54 UTC
